---
version: "3.5"

networks:
  default:
    name: ${DEMO_NAME}-network

volumes:
  dependency-check:
    name: ${DEMO_NAME}-dependency-check
  gitlab_config:
    name: ${DEMO_NAME}-gitlab_config
  gitlab_data:
    name: ${DEMO_NAME}-gitlab_data
  gitlab_logs:
    name: ${DEMO_NAME}-gitlab_logs
  gitlab_runner_config:
    name: ${DEMO_NAME}-gitlab_runner_config
  gitlab_runner_2_config:
    name: ${DEMO_NAME}-gitlab_runner_2_config
  gitlab_runner_3_config:
    name: ${DEMO_NAME}-gitlab_runner_3_config
  sonarqube_config:
    name: ${DEMO_NAME}-sonarqube_config
  sonarqube_data:
    name: ${DEMO_NAME}-sonarqube_data
  sonarqube_extensions:
    name: ${DEMO_NAME}-sonarqube_extensions
  sonarqube_logs:
    name: ${DEMO_NAME}-sonarqube_logs
  sonarqube_temp:
    name: ${DEMO_NAME}-sonarqube_temp
    driver_opts:
      type: tmpfs
      device: tmpfs

services:
  # The GitLab instance
  gitlab:
    container_name: ${DEMO_NAME}-gitlab
    environment:
      # These settings will be evaluated on load - see
      # https://docs.gitlab.com/omnibus/docker/#pre-configure-docker-container
      GITLAB_OMNIBUS_CONFIG: |
        external_url '${EXTERNAL_URL}'
        gitlab_rails['initial_root_password'] = '${GITLAB_PASSWORD}'
        gitlab_rails['rack_attack_git_basic_auth'] = {
        'enabled' => true,
        'ip_whitelist' => ['127.0.0.1'],
        'maxretry' => 10,
        'findtime' => 60,
        'bantime' => 3600
        }
        gitlab_rails['time_zone'] = 'Europe/Amsterdam'
        gitlab_rails['usage_ping_enabled'] = false
        letsencrypt['enable'] = false
        nginx['listen_https'] = false
        nginx['client_max_body_size'] = '0'
        puma['port'] = 3456
        prometheus_monitoring['enable'] = false
        gitlab_rails['initial_shared_runners_registration_token'] = "${REGISTRATION_TOKEN}"
      GITLAB_POST_RECONFIGURE_SCRIPT: /etc/gitlab/post-reconfigure.sh
    hostname: gitlab
    image: gitlab/gitlab-ce:${GITLAB_CE_VERSION}
    ports:
      # GitLab reads the nginx port number from EXTERNAL_URL
      - "127.0.0.1:${HTTP_PORT}:${HTTP_PORT}"
      - "127.0.0.1:${SSH_PORT}:22"
    restart: unless-stopped
    shm_size: "256m"
    stop_grace_period: 10m
    volumes:
      - gitlab_config:/etc/gitlab
      - gitlab_data:/var/opt/gitlab
      - gitlab_logs:/var/log/gitlab
      - ./gitlab-post-reconfigure.sh:/etc/gitlab/post-reconfigure.sh:ro

  # The runners
  gitlab-runner:
    container_name: ${DEMO_NAME}-gitlab-runner
    depends_on:
      - gitlab
    hostname: gitlab-runner
    image: gitlab/gitlab-runner:latest
    restart: unless-stopped
    volumes:
      - gitlab_runner_config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
      - dependency-check:/usr/share/dependency-check/data

  gitlab-runner-2:
    container_name: ${DEMO_NAME}-gitlab-runner-2
    depends_on:
      - gitlab
    hostname: gitlab-runner-2
    image: gitlab/gitlab-runner:latest
    restart: unless-stopped
    volumes:
      - gitlab_runner_2_config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
      - dependency-check:/usr/share/dependency-check/data

  gitlab-runner-3:
    container_name: ${DEMO_NAME}-gitlab-runner-3
    depends_on:
      - gitlab
    hostname: gitlab-runner-3
    image: gitlab/gitlab-runner:latest
    restart: unless-stopped
    volumes:
      - gitlab_runner_3_config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
      - dependency-check:/usr/share/dependency-check/data

  # Ephemeral containers which registers the runners
  gitlab-runner-registrar:
    container_name: ${DEMO_NAME}-gitlab-runner-registrar
    depends_on:
      - gitlab-runner
    entrypoint: /root/entrypoint.sh
    # Ensure that the script has access to the variable as defined in .env
    environment:
      - EXTERNAL_URL
      - REGISTRATION_TOKEN
    # Hostname needs to be similar to the runner it's registering
    hostname: gitlab-runner
    image: gitlab/gitlab-runner:latest
    volumes:
      - gitlab_runner_config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
      - ./gitlab-runner-registrar.sh:/root/entrypoint.sh:ro

  gitlab-runner-2-registrar:
    container_name: ${DEMO_NAME}-gitlab-runner-2-registrar
    depends_on:
      - gitlab-runner-2
    entrypoint: /root/entrypoint.sh
    # Ensure that the script has access to the variable as defined in .env
    environment:
      - EXTERNAL_URL
      - REGISTRATION_TOKEN
    # Hostname needs to be similar to the runner it's registering
    hostname: gitlab-runner-2
    image: gitlab/gitlab-runner:latest
    volumes:
      - gitlab_runner_2_config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
      - ./gitlab-runner-registrar.sh:/root/entrypoint.sh:ro

  gitlab-runner-3-registrar:
    container_name: ${DEMO_NAME}-gitlab-runner-3-registrar
    depends_on:
      - gitlab-runner-3
    entrypoint: /root/entrypoint.sh
    # Ensure that the script has access to the variable as defined in .env
    environment:
      - EXTERNAL_URL
      - REGISTRATION_TOKEN
    # Hostname needs to be similar to the runner it's registering
    hostname: gitlab-runner-3
    image: gitlab/gitlab-runner:latest
    volumes:
      - gitlab_runner_3_config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
      - ./gitlab-runner-registrar.sh:/root/entrypoint.sh:ro

  # Sonarqube
  sonarqube:
    container_name: ${DEMO_NAME}-sonarqube
    image: sonarqube:${SONARQUBE_VERSION}
    networks:
      default:
        aliases:
          - sonarqube.demo.local
    ports:
      - "127.0.0.1:${SONARQUBE_PORT}:9000"
    restart: unless-stopped
    stop_grace_period: 10m
    volumes:
      - sonarqube_config:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
      - sonarqube_temp:/opt/sonarqube/temp
